{{- if .Values.promtail.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "stellar-bounty.fullname" . }}-promtail
  labels:
    {{- include "stellar-bounty.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods", "services", "endpoints"]
    verbs: ["get", "watch", "list"]
{{- end }}
