import * as fc from 'fast-check';
import { validate } from 'class-validator';
import { CreateBountyDto, MAX_REWARD_AMOUNT } from './bounty.dto';

describe('Bounty DTO property-based tests', () => {
  const validOwnerAddress = 'GDTY76352AZN6ONTTQNTPSX52QTH7SME777Q275R6HURGX3CN4XZJ7F7';

  function createValidDto(rewardAmount: string): CreateBountyDto {
    const dto = new CreateBountyDto();
    dto.title = 'Property test bounty';
    dto.description = 'Generated by fast-check for property-based testing.';
    dto.ownerAddress = validOwnerAddress;
    dto.deadline = new Date(Date.now() + 86_400_000).toISOString();
    dto.rewardAmount = rewardAmount;
    return dto;
  }

  it('any valid whole-number rewardAmount within 1..MAX passes validation', async () => {
    await fc.assert(
      fc.asyncProperty(fc.bigInt({ min: 1n, max: MAX_REWARD_AMOUNT }), async (amount) => {
        const errors = await validate(createValidDto(amount.toString()));
        expect(errors).toHaveLength(0);
      }),
      { numRuns: 200 },
    );
  });

  it('rewardAmount zero or negative fails validation', async () => {
    await fc.assert(
      fc.asyncProperty(fc.bigInt({ max: 0n }), async (amount) => {
        const errors = await validate(createValidDto(amount.toString()));
        expect(errors.some((e) => e.property === 'rewardAmount')).toBe(true);
      }),
      { numRuns: 100 },
    );
  });

  it('rewardAmount exceeding MAX_REWARD_AMOUNT fails validation', async () => {
    await fc.assert(
      fc.asyncProperty(fc.bigInt({ min: MAX_REWARD_AMOUNT + 1n, max: MAX_REWARD_AMOUNT + 1000000n }), async (amount) => {
        const errors = await validate(createValidDto(amount.toString()));
        expect(errors.some((e) => e.property === 'rewardAmount')).toBe(true);
      }),
      { numRuns: 100 },
    );
  });

  it('any valid Stellar public key passes ownerAddress validation', async () => {
    await fc.assert(
      fc.asyncProperty(fc.string({ minLength: 56, maxLength: 56 }).filter((s) => /^G[1-9A-HJ-NP-Za-km-z]{55}$/.test(s)), async (address) => {
        const dto = createValidDto('10000000');
        dto.ownerAddress = address;
        const errors = await validate(dto);
        expect(errors.some((e) => e.property === 'ownerAddress')).toBe(false);
      }),
      { numRuns: 200 },
    );
  });

  it('invalid Stellar public key fails ownerAddress validation', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.oneof(
          fc.string({ minLength: 1, maxLength: 10 }),
          fc.string({ minLength: 57, maxLength: 100 }),
          fc.constant(''),
          fc.constant('NOT_A_KEY'),
        ),
        async (address) => {
          const dto = createValidDto('10000000');
          dto.ownerAddress = address;
          const errors = await validate(dto);
          expect(errors.some((e) => e.property === 'ownerAddress')).toBe(true);
        },
      ),
      { numRuns: 200 },
    );
  });

  it('random valid CreateBountyDto always passes validation', async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.string({ minLength: 1, maxLength: 200 }),
        fc.string({ minLength: 1, maxLength: 2000 }),
        fc.bigInt({ min: 1n, max: MAX_REWARD_AMOUNT }),
        fc.isoDateTime(),
        fc.constant(validOwnerAddress),
        async (title, description, rewardAmount, deadline, ownerAddress) => {
          const dto = new CreateBountyDto();
          dto.title = title;
          dto.description = description;
          dto.rewardAmount = rewardAmount.toString();
          dto.deadline = deadline;
          dto.ownerAddress = ownerAddress;
          const errors = await validate(dto);
          expect(errors).toHaveLength(0);
        },
      ),
      { numRuns: 150 },
    );
  });
});
